# action.yml
name: 'Create preconfigured keycloak instance'
description: 'Run Keycloak, create admin, import realm'
inputs:
  admin-account-name:  # id of input
    description: 'admin account name'
    required: true
    default: 'admin'
  admin-account-password:  # id of input
    description: 'admin account password'
    required: true
    default: 'admin'
  realm-path:  # id of input
    description: 'realm-path'
    required: true
    default: 'realm-export.json'
runs:
  using: 'docker'
  image: 'docker://jboss/keycloak'
  args:
    - -DKEYCLOAK_USER=${{inputs.admin-account-name }}
    - -DKEYCLOAK_PASSWORD=${{inputs.admin-account-password }}
    - -DKEYCLOAK_IMPORT=${{inputs.realm-path }}
